import Head from 'next/head'
import Image from 'next/image';
import Features from '../components/Features';
import Herosection from '../components/Herosection';
import SectionTitle from '../components/SectionTitle';
import Categories from './../components/Categorie';
// import Categories from './../components/Categories';
import Offers from './../components/Offers';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Epic Wear - Wear the Epic Way</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Herosection />
      </div>
      <Features />
      <div>
      <Offers />
        <SectionTitle title="CATEGORIES" />
        <Categories />
      </div>
      <div>
        <SectionTitle title="FEATURED PRODUCTS" />
      </div>

    </div>
  )
}
