import Head from 'next/head'
import Features from '../components/Features';
// import Herosection from '../components/Herosection';
import SectionTitle from '../components/SectionTitle';
import Categorie from './../components/Categorie';
// import Categories from './../components/Categories';
import Offers from './../components/Offers';
import Hero from "../components/Hero"
import Poster from '../components/Poster';
import Featuresproduct from '../components/Featuresproduct';


const Home = () => {


  return (
    <>
      <Head>
        <title>Epic Wear - Wear the Epic Way</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
      </div>
      <Features />
      <div>
        <SectionTitle title="CATEGORIES" />
        <Categorie />
      </div>
      <div>
        <Offers />
        <Poster />
      </div>
      <div>
        <SectionTitle title="FEATURED PRODUCTS" />
        <Featuresproduct />
      </div>
    </>
  )
}

export default Home;