import Head from 'next/head'
import Image from 'next/image' 

export default function Home() {
  return (
    <div >
      <Head>
        <title>Epic Wear - Wear the Epic Way</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <div>
          <img className="object-cover h-auto w-full " src='/mainposter.jpg' alt=''></img>
        </div>
      
    </div>
  )
}
